- id: '1690311230553'
  alias: WWWP_Set_Betriebsart
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_betriebsart_set
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 12
      slave: 1
      value: "{% if is_state('input_select.wwwp_betriebsart_set', 'WP+EL') %}\n 3\n{%
        elif is_state('input_select.wwwp_betriebsart_set', 'WP+Kessel') %}\n 5\n{%
        elif is_state('input_select.wwwp_betriebsart_set', 'WP') %}\n 1\n{% elif is_state('input_select.wwwp_betriebsart_set',
        'EL') %}\n 2\n{% elif is_state('input_select.wwwp_betriebsart_set', 'Kessel')
        %}\n 4\n{% elif is_state('input_select.wwwp_betriebsart_set', 'Off') %}\n
        0\n{% else %}\n none\n{%- endif -%}\n"
  mode: single
- id: '1690320814287'
  alias: WWWP_Set_Legionellenfunktion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_legionellenfunktion
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 13
      slave: 1
      value: "{% if is_state('input_select.wwwp_legionellenfunktion', 'Aus') %}\n
        0\n{% elif is_state('input_select.wwwp_legionellenfunktion', '60C') %}\n 1\n{%
        elif is_state('input_select.wwwp_legionellenfunktion', '65C') %}\n 2\n{% else
        %}\n none\n{%- endif -%}\n"
  mode: single
- id: '1690320874098'
  alias: WWWP_Set_PV_Modus
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_pv_modus
  - platform: state
    entity_id:
    - automation.set_pv_state_depends_on_soc
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 17
      slave: 1
      value: "{% if is_state('input_select.wwwp_pv_modus', 'WP+EL') %}\n 3\n{% elif
        is_state('input_select.wwwp_pv_modus', 'WP') %}\n 1\n{% elif is_state('input_select.wwwp_pv_modus',
        'EL') %}\n 2\n{% elif is_state('input_select.wwwp_pv_modus', 'Aus') %}\n 0\n{%
        else %}\n none\n{%- endif -%}\n"
  mode: single
- id: '1690320942867'
  alias: WWWP_Set_Feriendauer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_feriendauer
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 20
      slave: 1
      value: "{% if is_state('input_select.wwwp_feriendauer', 'Aus') %}\n 0\n{% elif
        is_state('input_select.wwwp_feriendauer', '1 Woche') %}\n 1\n{% elif is_state('input_select.wwwp_feriendauer',
        '2 Wochen') %}\n 2\n{% elif is_state('input_select.wwwp_feriendauer', '3 Wochen')
        %}\n 3\n{% elif is_state('input_select.wwwp_feriendauer', '3 Tage') %}\n 4\n{%
        else %}\n none\n{%- endif -%}\n"
  mode: single
- id: '1690489006082'
  alias: WWWP_Set_KWL
  description: Kontrollierte Wohnraumlüftung
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_kwl
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 16
      slave: 1
      value: "{% if is_state('input_select.wwwp_kwl', 'Aus') %}\n 0\n{% elif is_state('input_select.wwwp_kwl',
        'Low') %}\n 1\n{% elif is_state('input_select.wwwp_kwl', 'Mid') %}\n 2\n{%
        elif is_state('input_select.wwwp_kwl', 'High') %}\n 3\n{% else %}\n none\n{%-
        endif -%}\n"
  mode: single
- id: '1690589006083'
  alias: WWWP_Set_WP_LS
  description: Lufterstufe Einstellung
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_wp_ls
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 15
      slave: 1
      value: "{% if is_state('input_select.wwwp_wp_ls', 'Niedrig') %}\n 0\n{% elif
        is_state('input_select.wwwp_wp_ls', 'Mittel') %}\n 1\n{% elif is_state('input_select.wwwp_wp_ls',
        'Hoch') %}\n 2\n{% else %}\n none\n{%- endif -%}\n"
  mode: single
- id: '1690689006084'
  alias: WWWP_Set_Abtauart
  description: Abtauart
  trigger:
  - platform: state
    entity_id:
    - input_select.wwwp_abtauart
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 26
      slave: 1
      value: "{% if is_state('input_select.wwwp_Abtauart', 'Gas') %}\n 0\n{% elif
        is_state('input_select.wwwp_Abtauart', 'Luft') %}\n 1\n{% elif is_state('input_select.wwwp_Abtauart',
        'TminRL') %}\n 2\n{% else %}\n none\n{%- endif -%}\n"
  mode: single
- id: ecodesign.speed_ls1_set
  alias: Ecodesign Speed LS1 SET
  trigger:
  - platform: state
    entity_id: input_number.ecodesign_speed_ls1
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 30
      slave: 1
      value: '{{ states(''input_number.ecodesign_speed_ls1'') | int }}'
- id: ecodesign.speed_ls2_set
  alias: Ecodesign Speed LS2 SET
  trigger:
  - platform: state
    entity_id: input_number.ecodesign_speed_ls2
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 31
      slave: 1
      value: '{{ states(''input_number.ecodesign_speed_ls2'') | int }}'
- id: ecodesign.speed_ls3_set
  alias: Ecodesign Speed LS3 SET
  trigger:
  - platform: state
    entity_id: input_number.ecodesign_speed_ls3
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      address: 32
      slave: 1
      value: '{{ states(''input_number.ecodesign_speed_ls3'') | int }}'
- id: 'ecodesign_tstart_1'
  alias: "Update Timer Start Time"
  trigger:
  - platform: state
    entity_id: input_datetime.ecodesign_tstart
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      slave: 1
      address: 8  # Address for start hours
      value: "{{ states('input_datetime.ecodesign_tstart').attributes.hour }}"
  - service: modbus.write_register
    data:
      hub: wwwp
      slave: 1
      address: 9  # Address for start minutes      
      value: "{{ states('input_datetime.ecodesign_tstart').attributes.minute }}"
- id: 'ecodesign_tstop_2'
  alias: "Update Timer Stop Time"
  trigger:
  - platform: state
    entity_id: input_datetime.ecodesign_tstop
  action:
  - service: modbus.write_register
    data:
      hub: wwwp
      slave: 1
      address: 10  # Address for stop hours
      value: "{{ states('input_datetime.ecodesign_tstop').attributes.hour }}"
  - service: modbus.write_register
    data:
      hub: wwwp
      slave: 1
      address: 11  # Address for stop minutes
      value: "{{ states('input_datetime.ecodesign_tstop').attributes.minute }}"
